### ISSUE TITLE
Support for 3 digit python version

### ISSUE THREAD

**Issue by Grekkq** [diodonfrost/ansible-role-python#3]
##### SUMMARY
During installation of python version >3.9 we encounter a problem with name of the installation directory, in the default `python_path` var you use `python_version[:3]` to get just main part but it generates problems when trying to install versions where there are 3 significant digits (eg. 3.10). Maybe we could split it by `.` and just get everything before second `.` ([potential stackoverflow solution](https://stackoverflow.com/a/55194553/12444149))?

##### STEPS TO REPRODUCE

Install python in version >3.9
```yaml
roles:
  - role: diodonfrost.python
    become: yes
    vars:
      python_version: 3.10.4
```

##### EXPECTED RESULTS

```paste below
/usr/local/python3.10/ would be default path to installation directory
```

##### ACTUAL RESULTS

```paste below
/usr/local/python3.1/ only first 3 characters are being passed as a directory name
```
